language: objective-c  #1
osx_image: xcode10.2 #2
xcode_project: Bedrock.xcodeproj #3
xcode_scheme: Bedrock #4
xcode_sdk: iphonesimulator12.2

before_install:
  - brew install carthage

install:
  - carthage update --platform iOS

script: 
  - xcodebuild -project Bedrock.xcodeproj -scheme Bedrock -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - xcodebuild test -project Bedrock.xcodeproj -scheme Bedrock -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' -sdk iphonesimulator
